//
// Created by Sam on 8/1/2018.
//

#ifndef TRAGETORY_GENERATION_POLYNOMIAL_SOLVER_H
#define TRAGETORY_GENERATION_POLYNOMIAL_SOLVER_H

void verify_JMT();

#endif //TRAGETORY_GENERATION_POLYNOMIAL_SOLVER_H
